learnweb/moodle-tool_lifecycle

adminlib.php
classes/cleanup_processor.php
classes/entity/process.php
classes/entity/trigger_subplugin.php
classes/manager/process_manager.php
classes/manager/step_manager.php
classes/manager/trigger_manager.php
codecov.yml
db/install.xml
tests/backup_manager_test.php
tests/generator/lib.php
tests/persistence/persist_process_data_test.php
tests/persistence/persist_process_test.php
tests/persistence/persist_step_test.php
tests/settings_manager_test.php

Added several tests for entity and manager classes

Increased test coverage

---

classes/table/interaction_attention_table.php
classes/table/interaction_remaining_table.php

and interaction_attention_table.
Closing #3.

Adding category column in interaction_remaining_table

---

adminlib.php

It it only a small visual glitch but the 'Back' button could be perfectly aligned.
Best,
Luca

Align back button.

---

adminlib.php

I notices some pages did display a title other than similar ones.

Set page title for Workflow Settings page.

---

adminlib.php
classes/form/form_upload_workflow.php
classes/local/backup/backup_lifecycle_workflow.php
classes/local/backup/restore_lifecycle_workflow.php
classes/manager/settings_manager.php
classes/manager/step_manager.php
classes/manager/workflow_manager.php
classes/table/active_workflows_table.php
classes/table/workflow_definition_table.php
lang/en/tool_lifecycle.php
lib.php
renderer.php
step/email/lang/en/lifecyclestep_email.php
tests/backup_and_restore_workflow_test.php
tests/generator/lib.php

This feature enables to backup workflow definitions and share them in the community. This should make it easier for admins to rely on definitions of other users. Afterwards they can adjust the workflows in small details according to their needs.

Backup and Restore Functionality for workflow definitions

---

lang/en/tool_lifecycle.php

Reword setting description

---

classes/entity/workflow.php
classes/local/backup/restore_lifecycle_workflow.php
classes/manager/workflow_manager.php
classes/table/active_automatic_workflows_table.php
classes/table/active_manual_workflows_table.php
classes/table/deactivated_workflows_table.php
classes/table/workflow_definition_table.php
db/install.xml
db/upgrade.php
tests/workflow_actions_testcase.php
version.php

Removed obsolete db field active from workflow entity

---

classes/table/course_backups_table.php
downloadbackup.php
lang/en/tool_lifecycle.php

Add functionality to download course backups

---

classes/manager/process_manager.php
step/lib.php

Adding rollback functionality

---

classes/table/active_processes_table.php

Make Active Processes sortable by step

---

classes/event/process_proceeded.php
classes/event/process_rollback.php
classes/event/process_triggered.php
classes/manager/process_manager.php
classes/processor.php
lang/en/tool_lifecycle.php
tests/process_status_message_test.php

Add events for triggering/proceeding/rolling back processes

---

classes/manager/interaction_manager.php
classes/view_controller.php

Prevent an error if a step has no interaction lib defined

---

classes/table/step_table.php

Fix sort order of non editable workflow step views

---

classes/manager/workflow_manager.php
tests/generator/lib.php
tests/workflow_activate_disable_duplicate_test.php

Copy the displaytitle upon duplicate

---

classes/table/interaction_attention_table.php
classes/table/interaction_remaining_table.php
classes/table/interaction_table.php

Also fixes #69. Integrates changes of #81

Better interactiontables 2

---

lang/de/tool_lifecycle.php
lang/en/tool_lifecycle.php
step/createbackup/lang/de/lifecyclestep_createbackup.php
step/deletecourse/lang/de/lifecyclestep_deletecourse.php
step/duplicate/lang/de/lifecyclestep_duplicate.php
step/email/lang/de/lifecyclestep_email.php
trigger/categories/lang/de/lifecycletrigger_categories.php
trigger/delayedcourses/lang/de/lifecycletrigger_delayedcourses.php
trigger/manual/lang/de/lifecycletrigger_manual.php
trigger/manual/lang/en/lifecycletrigger_manual.php
trigger/sitecourse/lang/de/lifecycletrigger_sitecourse.php
trigger/specificdate/lang/de/lifecycletrigger_specificdate.php
trigger/startdatedelay/lang/de/lifecycletrigger_startdatedelay.php

Currently not translated Life Cycle

German Language Strings

---

view.php

Looks like this with boost theme

Add breadcrumbs for view.php

---

adminlib.php

Adding some space to Workflow steps form.

---

classes/processor.php

If you create a workflow with no steps and run cron, the following error occurs:
```
PHP Notice:  Trying to get property 'subpluginname' of non-object in /var/www/public/moodle/admin/tool/lifecycle/classes/processor.php on line 110
```
This prevents the error.
Alternatively, it could also be disallowed to create a workflow without steps, but I since it doesn't do any harm (and I just created some workflows without steps for testing ), I've fixed it this way for now.

Fixes error when processing workflow without steps.

---

classes/local/table/interaction_remaining_table.php
classes/privacy/provider.php
lang/en/tool_lifecycle.php
tests/privacy_test.php

This fixes #50.
All data is currently regarded to be at System context.

Implementing Privacy

---

classes/task/lifecycle_cleanup_task.php
db/tasks.php
lang/en/tool_lifecycle.php
version.php

A new task is added that deletes all delays which expired more than 60 days ago.

Add delay cleanup

---

classes/local/table/active_processes_table.php
classes/local/table/course_backups_table.php
classes/local/table/interaction_table.php

It should be possible for the active processes table to handle multilang course names.
Best,
Luca

Support multilang course names.

---

classes/local/manager/backup_manager.php

Delete backup files in file area after copying

---

classes/local/table/delayed_courses_table.php

Restructure Delay-SQL-Query to avoid full joins which are not supported by MySQL.
Fixes #113

Fix Delay View for MySQL

---

trigger/specificdate/lang/de/lifecycletrigger_specificdate.php
trigger/specificdate/lang/en/lifecycletrigger_specificdate.php
trigger/specificdate/lib.php

As i described in issue#147, the specificdate-trigger was buggy and somewhat complicated.
I refined it so it works properly and also triggers the courses if the date of 'today' is put in the settings.
The old logic didn't trigger if the Workflow with a specificdate-trigger of today was activated.
Greetings ;)

Refined 'specificdate'-trigger, so it works and triggers 'todays'-date. issue#147

---

activeworkflows.php
coursebackups.php
delayedcourses.php
errors.php
renderer.php
styles.css
templates/workflowoverview.mustache
workflowdrafts.php

WIP - display some type of navigation for the most common Pages 
TODO:
- adjust to design
- show on settings page

WIP add secondary navigation TODO: add to settings page

---

.github/workflows/moodle-ci.yml
templates/workflowoverview.mustache
version.php

- Workflow view, navigation structure and general redesign (#155)
- Update for Moodle 4.1 (#166)
- Added null privacy providers for all subplugins (#156)
- Improved logic for lifecycletrigger_specificdate (#151)

Update for Moodle 4.1

---

.github/workflows/moodle-ci.yml
.github/workflows/moodle-release.yml
classes/local/backup/backup_lifecycle_workflow.php
version.php

Needs a new release.
Changelog:
- Overhaul of navigation and a new overview screen for workflows #155 
- Privacy providers for all subplugins #156 
- Bugfixes

Update for Moodle 4.2

---

classes/local/manager/workflow_manager.php

Disabling a workflow just removes it from the sort order without updating the `sortindex` of the remaining active workflow. This leaves a gap in the `sortindex`, which can cause different problems: eg., you can't "move up" the workflow which was immediately below the disabled one, or "move down" the one which was above it. Or, if you now activate a new workflow, it will get the same `sortindex` as the previously last one…
This is the root cause of the problems reported in issue #128.
This PR adds a function to `workflow_manager.php` to rearrange the `sortindex` of the remaining workflows when disabling a workflow.

Update `sortindex` of remaining workflows when disabling a workflow

---

classes/local/table/active_manual_workflows_table.php

The columns in active_manual_workflows_table shouldn't be sortable

---

lang/en/tool_lifecycle.php

Missing cachedef_application string

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/config.json
.gitignore
activeprocesses.php
activeworkflows.php
confirmation.php
coursebackups.php
createworkflowfromexisting.php
deactivatedworkflows.php
delayedcourses.php
editelement.php
editworkflow.php
errors.php
step/adminapprove/index.php
uploadworkflow.php
version.php
workflowdrafts.php
workflowoverview.php

> **Note:** Please fill out all required sections and remove irrelevant ones.
---
Please describe the purpose of this PR in a few sentences.
- What feature or bug does it address?
- Why is this change or addition necessary?
- What is the expected behavior after the change?
---
Please confirm the following (check all that apply):
should not appear on the productive branch.
updated the `version.php`.
I ran all tests thoroughly checking for errors. I checked if bootstrap had any changes/deprecations that require
changes in the plugins UI.
---
- Related to #[IssueNumber]
---
Any other relevant information.
---

Hotfix 405 Permissions
