- classes/manager/delayed_courses_manager.php
- classes/processor.php
- step/email/lib.php
- trigger/categories/lib.php
- trigger/categories/tests/trigger_test.php
- trigger/delayedcourses/lib.php
- trigger/delayedcourses/tests/trigger_test.php
- trigger/lib.php
- trigger/sitecourse/lib.php
- trigger/specificdate/lib.php
- trigger/startdatedelay/lib.php
- trigger/startdatedelay/tests/trigger_test.php
For huge amounts of courses, the trigger processing is currently very slow.
This PR introduces a new function for trigger, in which they can extend the where sql statement of the course recordset, which is constructed before actually calling the call_trigger() function of each trigger.
> Improved processing of triggers for huge course amounts

- classes/form/form_step_instance.php
- classes/form/form_trigger_instance.php
- classes/form/form_workflow_instance.php
- lang/en/tool_lifecycle.php
- step/duplicate/classes/form_duplicate.php
- step/email/lang/en/lifecyclestep_email.php
- step/email/lib.php
- tests/behat/activate_workflow.feature
- tests/behat/interaction.feature
- trigger/manual/lang/en/lifecycletrigger_manual.php
- trigger/manual/lib.php
- trigger/startdatedelay/lang/en/lifecycletrigger_startdatedelay.php
- trigger/startdatedelay/lib.php
This commit gives help texts and help icons next to the labels.
Note that the labels have to be edited in the lang files. As of now, they just replicate the label text which is pretty useless.
> Adding help icons near to form labels.

- .travis.yml
- classes/manager/settings_manager.php
- trigger/categories/lang/en/lifecycletrigger_categories.php
- trigger/categories/lib.php
Enhances "categories" trigger to use autocompletion for category selection instead of comma separated input of IDs for better usability.
For storing the array of IDs in database, I modified settings_manager to implode arrays. Not quite sure if this is the best way in all cases or if there is a better practice, but I think it's totally fine here.
> Enhanced "categories" trigger to use autocompletion for category selection

- step/deletecourse/db/upgrade.php
- step/deletecourse/lang/en/lifecyclestep_deletecourse.php
- step/deletecourse/lib.php
- step/deletecourse/version.php
Currently, there is no limitation, how many courses might be deleted per cron job run. This might be quite a lot for huge platforms. Since a course deletion takes a lot of time, this patch allows to reduce the amount of courses, which can be deleted within one cron job run.
> Add a configuration to limit the number of courses deleted per cron

- step/createbackup/db/upgrade.php
- step/createbackup/lang/en/lifecyclestep_createbackup.php
- step/createbackup/lib.php
- tests/generator/lib.php
- tests/manually_triggered_process_test.php
- version.php
This adds a configuration to restrict the number of backups that can be done per cron.
This fixes #46
> Limit the number of backups per cron

- classes/table/step_table.php
When you hide or show colums in the workflow steps table, moodle throws a missingparam error. Here is the fix for that.
> Fixes error when hiding colums in workflow steps table.

- db/subplugins.json
- db/subplugins.php
Escaping the slashes in subplugins.json is not required, but allowed, and since all json files in the moodle core do it that way, I did the same.
> Add subplugins.json

- step/deletecourse/lib.php
The delete course step should override the `process_waiting_course` function in order to process waiting courses correctly. Courses will be waiting in this step when `$numberofdeletions` exceeds the maximum.
You may also consider to change the implementation of `\tool_lifecycle\step\libbase::process_waiting_course()`. Maybe throw an exception. If your `process_course()` may return a waiting response, you probably want to override the `process_waiting_course` function in your class.
> Delete course step: delete waiting courses

- classes/local/manager/backup_manager.php
- downloadbackup.php
- lang/en/tool_lifecycle.php
- settings.php
- version.php
This PR allows to set a path for the backup dir. This way it is easier for system administrators to place the backups folder in a separate storage space.
> Add config for the backup dir path

- step/lib.php
This changes the default of just proceeding a course. However, I can not
think of a scenario were this would make sense.
Folllow up on #103
> Throw exception in process_waiting_course if called and not overridden

- classes/local/manager/backup_manager.php
Currently, the backup settings from the general backups are used for creation of backups within tool_lifecycle. We changed this for two reasons.
The first one is the obvious: tool_lifecycle creates the backups automatically.
The second reason is that the backups of tool_lifecycle should have the same contents as the automated backups by moodle. This way, we can delete the automated moodle backups, when we finally delete the course.
> Use backup settings from automated backups

- classes/local/manager/process_manager.php
- db/events.php
- db/upgrade.php
- step/lib.php
- version.php
Deletes a process when the corresponding course is deleted and calls the `abort_course()` method of the steplib of the current step.
Adresses learnweb/moodle-lifecyclestep_adminapprove#22
> Abort and delete processes whose courses got deleted

- trigger/categories/lib.php
This adds category paths on settings page. 
It's needed to when there's multiple categories with same name.
This was quite straight forward to add by using following moodle core class 
core_course_category::make_categories_list()
> Category trigger : select categories with paths

- lang/en/tool_lifecycle.php
Adds a language string for the cache definition to fix an error in the execution of the unit tests.
> MBS-6313: Adding Lang String for cache definition

- tests/process_error_test.php
Using `tool_lifecycle` with PHP 8.0 results in a unit test error because an error message is being asserted which has changed in PHP 8.0.
I made the patch backwards compatible for PHP 7.4
> MBS-7081: Fix unit test error in process_error_test.php for PHP 8.0

- step/email/lib.php
We noticed that all enrolled users with the 'lifecyclestep/email:preventdeletion' capability are 
informed by the E-Mail-Step.
We think only the users with `ENROL_USER_ACTIVE` should be informed.
It could also be a separate setting, but for now i changed the way `$userstobeinformed` is retrieved.
Greetings 
Felix
> Inform only active users by email step

- lang/de/tool_lifecycle.php
- lang/en/tool_lifecycle.php
- settings.php
- templates/workflowoverview.mustache
- workflowoverview.php
Closes #170 
I decided to make this feature an admin setting. So if an admin experiences performance issues he can deactive the config setting and still will have the opportunity to configure workflows.
This also can be seen as workaround for #169, not a real fix for this issue though :-)
> Fix workflowoverview for big instances

- classes/local/backup/restore_lifecycle_workflow.php
- classes/local/manager/workflow_manager.php
- tests/behat/manual_trigger.feature
- tests/behat/upload_workflow.feature
- tests/fixtures/simpleworkflow.xml
- uploadworkflow.php
> fix upload workflow

- trigger/manual/lang/de/lifecycletrigger_manual.php
- trigger/manual/lang/en/lifecycletrigger_manual.php
Hi!
This should solve #176 . The help text was a little bit misleading because it produced an error (icon not showing up). I'm not sure if moodle had recently changed something regarding the integration of the icons. 
Kind regards!
> Improve help text for integration of icons (manual trigger)

- classes/local/manager/step_manager.php
- classes/local/manager/trigger_manager.php
There is a very subtle bug in the `remove_from_sortindex` function in `classes/local/manager/step_manager.php`. It looks like it should affect only the steps in the same workflow, but actually the `workflowid` is only passed as a parameter, but not _actually_ used in the SELECT condition. So, what actually happens is that _every_ workflow (that have enough) steps is changed when you delete a step from any workflow. Resulting in reordering of steps and other problems, like being unable to reorder steps anymore.
How to reproduce:
1. Create two workflows. First with 3 steps, the Second with at least one step. (Choose whatever steps you want.)
2. Remove the first step in the Second workflow.
3. Check the sortindexes for the First workflow's steps in the DB, it's now `1, 1, 2` instead of `1, …
> Fix `sortindex` handling on step deletion

- classes/local/backup/restore_lifecycle_workflow.php
- classes/local/form/form_upload_workflow.php
- lang/en/tool_lifecycle.php
- renderer.php
- step/lib.php
- tests/backup_and_restore_workflow_test.php
- trigger/categories/lang/de/lifecycletrigger_categories.php
- trigger/categories/lang/en/lifecycletrigger_categories.php
- trigger/categories/lib.php
- trigger/lib.php
- uploadworkflow.php
> Check backup consistency before importing workflow

- classes/local/form/form_step_instance.php
- step/lib.php
Regards:
https://github.com/learnweb/moodle-tool_lifecycle/issues/225
> Add validation for step form

- classes/processor.php
This creates a stdClass object populating only the id, presenting as a course object. This allows steps to run after a course has been deleted. 
Closes #222.
> Allow steps to run when course no longer exits (#222)

- classes/event/process_proceeded.php
- classes/event/process_rollback.php
- classes/event/process_triggered.php
- classes/local/entity/process.php
- classes/local/manager/process_manager.php
- classes/processor.php
- tests/process_status_message_test.php
> Use field courseid for logging events

- classes/local/manager/workflow_manager.php
Scenario:
When a workflow is deactivated the assigned sortindex is "missing" in the workflow table.
If you want to move another, still active workflow to this position, a fatal error occurs:
This patch prevents this fatal error by omitting changes to a workflow which does not exist.
> fix error when otherindex does not exist
